"use client";

import { useEffect, useState } from "react";
import { Building2, ImagePlus, MapPin, Plus, Search, Trash2, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { API_URL, criarImovel, enviarFotoImovel, excluirImovel, getClientes, getImoveis, type Cliente, type Imovel } from "@/lib/api";

const moeda = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default function Imoveis() {
  const [imoveis, setImoveis] = useState<Imovel[]>([]); const [clientes, setClientes] = useState<Cliente[]>([]);
  const [busca, setBusca] = useState(""); const [erro, setErro] = useState(""); const [foto, setFoto] = useState<File | null>(null);
  const [form, setForm] = useState({ titulo: "", tipo: "Casa", endereco: "", descricao: "", valor: "", condominio: "", cliente_id: "", dia: "10" });
  async function carregar() { try { const [lista, pessoas] = await Promise.all([getImoveis(busca), getClientes()]); setImoveis(lista); setClientes(pessoas); } catch (e) { setErro(e instanceof Error ? e.message : "Não foi possível carregar os imóveis."); } }
  useEffect(() => { carregar(); }, [busca]); // eslint-disable-line react-hooks/exhaustive-deps
  async function salvar() {
    const aluguel = Math.round(Number(form.valor.replace(",", ".")) * 100); const condominio = Math.round(Number((form.condominio || "0").replace(",", ".")) * 100);
    if (!form.titulo.trim() || !aluguel) { setErro("Informe o título e o valor do aluguel."); return; }
    try { const criado = await criarImovel({ titulo: form.titulo, tipo: form.tipo, endereco: form.endereco, descricao: form.descricao, valor_aluguel_centavos: aluguel, taxa_condominio_centavos: condominio, cliente_id: form.cliente_id || undefined, dia_vencimento: form.cliente_id ? Number(form.dia) : undefined }); if (foto) await enviarFotoImovel(criado.id, foto); setForm({ titulo: "", tipo: "Casa", endereco: "", descricao: "", valor: "", condominio: "", cliente_id: "", dia: "10" }); setFoto(null); setErro(""); carregar(); } catch (e) { setErro(e instanceof Error ? e.message : "Não foi possível salvar o imóvel."); }
  }
  async function apagar(id: string) { if (window.confirm("Excluir este imóvel? As cobranças já criadas serão preservadas no histórico.")) { await excluirImovel(id); carregar(); } }
  return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">Locação imobiliária</p><h1 className="mt-1 text-2xl font-semibold text-slate-900">Imóveis</h1><p className="mt-1 text-sm text-slate-500">Cadastre imóveis disponíveis ou vinculados a um morador.</p></div><div className="rounded-full bg-indigo-50 px-3 py-2 text-sm font-medium text-primary">{imoveis.filter(i => i.status === "alugado").length} alugado(s)</div></div>
    <Card className="mt-6 p-5"><div className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-50 text-primary"><Building2 size={18}/></div><div><h2 className="font-semibold text-slate-800">Novo imóvel</h2><p className="text-xs text-slate-500">Ao escolher um cliente, o imóvel fica marcado como alugado.</p></div></div><div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-3"><input value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} placeholder="Ex.: Casa Alphaville 12" className="rounded-lg border border-slate-200 p-2.5 text-sm"/><select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} className="rounded-lg border border-slate-200 p-2.5 text-sm">{["Casa","Apartamento","Sala comercial","Kitnet","Terreno","Galpão","Outro"].map(x=><option key={x}>{x}</option>)}</select><input value={form.endereco} onChange={e=>setForm({...form,endereco:e.target.value})} placeholder="Endereço" className="rounded-lg border border-slate-200 p-2.5 text-sm"/><input value={form.valor} onChange={e=>setForm({...form,valor:e.target.value})} inputMode="decimal" placeholder="Aluguel mensal (R$)" className="rounded-lg border border-slate-200 p-2.5 text-sm"/><input value={form.condominio} onChange={e=>setForm({...form,condominio:e.target.value})} inputMode="decimal" placeholder="Condomínio (opcional)" className="rounded-lg border border-slate-200 p-2.5 text-sm"/><select value={form.cliente_id} onChange={e=>setForm({...form,cliente_id:e.target.value})} className="rounded-lg border border-slate-200 p-2.5 text-sm"><option value="">Disponível — sem morador</option>{clientes.map(c=><option value={c.id} key={c.id}>{c.nome}</option>)}</select>{form.cliente_id && <input type="number" min="1" max="31" value={form.dia} onChange={e=>setForm({...form,dia:e.target.value})} placeholder="Dia de vencimento" className="rounded-lg border border-slate-200 p-2.5 text-sm"/>}<label className="flex cursor-pointer items-center gap-2 rounded-lg border border-dashed border-slate-300 px-3 py-2.5 text-sm text-slate-500"><ImagePlus size={17}/>{foto ? foto.name : "Adicionar foto"}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFoto(e.target.files?.[0] ?? null)} className="hidden"/></label><textarea value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})} placeholder="Descrição (opcional)" className="min-h-10 rounded-lg border border-slate-200 p-2.5 text-sm md:col-span-2"/></div><Button onClick={salvar} className="mt-4"><Plus size={16}/> Salvar imóvel</Button></Card>
    <Card className="mt-5 overflow-hidden p-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-4"><div><h2 className="font-semibold text-slate-800">Carteira de imóveis</h2><p className="text-xs text-slate-500">{imoveis.length} imóvel(is) encontrado(s)</p></div><label className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Pesquisar imóvel ou morador" className="w-72 max-w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm"/></label></div><div className="grid grid-cols-1 gap-4 p-4 md:grid-cols-2 lg:grid-cols-3">{imoveis.length === 0 ? <p className="col-span-full py-12 text-center text-sm text-slate-400">Nenhum imóvel cadastrado.</p> : imoveis.map(i=><article key={i.id} className="overflow-hidden rounded-xl border border-slate-200"><div className="relative flex h-36 items-center justify-center bg-slate-100">{i.foto_nome ? <img src={`${API_URL}/imoveis/${i.id}/foto`} alt={i.titulo} className="h-full w-full object-cover"/> : <Building2 className="text-slate-300" size={34}/>}<span className={`absolute right-3 top-3 rounded-full px-2 py-1 text-xs font-medium ${i.status === "alugado" ? "bg-emerald-50 text-emerald-700" : "bg-white text-slate-600"}`}>{i.status === "alugado" ? "Alugado" : "Disponível"}</span></div><div className="p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold text-slate-800">{i.titulo}</p><p className="text-xs text-slate-500">{i.tipo}</p></div><button onClick={()=>apagar(i.id)} className="text-slate-400 hover:text-red-600"><Trash2 size={17}/></button></div>{i.endereco && <p className="mt-2 flex items-center gap-1 text-xs text-slate-500"><MapPin size={13}/>{i.endereco}</p>}<p className="mt-3 text-lg font-semibold text-primary">{moeda.format(i.valor_aluguel)}<span className="text-xs font-normal text-slate-500">/mês</span></p>{i.cliente_nome && <p className="mt-2 flex items-center gap-1 text-sm text-slate-600"><UserRound size={14}/>{i.cliente_nome} · vence dia {i.dia_vencimento}</p>}</div></article>)}</div></Card>{erro && <p className="mt-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{erro}</p>}</div>;
}
