"use client";

import { useEffect, useState } from "react";
import { Bell, Check, CircleDollarSign, Plus, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { criarCobranca, enviarLembreteCobranca, getCobrancas, getImoveis, marcarCobranca, type Cobranca, type Imovel } from "@/lib/api";

const hoje = new Date().toISOString().slice(0, 10); const mesAtual = hoje.slice(0, 7);
const moeda = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default function Cobrancas() {
  const [mes, setMes] = useState(mesAtual); const [cobrancas, setCobrancas] = useState<Cobranca[]>([]); const [imoveis, setImoveis] = useState<Imovel[]>([]); const [erro, setErro] = useState(""); const [enviando, setEnviando] = useState("");
  const [form, setForm] = useState({ imovel_id: "", vencimento: hoje, valor: "" });
  async function carregar() { try { const [lista, carteira] = await Promise.all([getCobrancas(mes), getImoveis()]); setCobrancas(lista); setImoveis(carteira.filter(i=>i.status === "alugado")); } catch (e) { setErro(e instanceof Error ? e.message : "Não foi possível carregar as cobranças."); } }
  useEffect(()=>{ carregar(); }, [mes]); // eslint-disable-line react-hooks/exhaustive-deps
  const selecionado = imoveis.find(i=>i.id===form.imovel_id);
  async function criar() { if (!form.imovel_id) { setErro("Selecione um imóvel alugado."); return; } try { await criarCobranca({ imovel_id: form.imovel_id, competencia: mes, vencimento: form.vencimento, valor_centavos: form.valor ? Math.round(Number(form.valor.replace(",", "."))*100) : undefined }); setForm({ imovel_id:"", vencimento:hoje, valor:"" }); setErro(""); carregar(); } catch (e) { setErro(e instanceof Error ? e.message : "Não foi possível criar a cobrança."); } }
  async function pagar(id: string) { try { await marcarCobranca(id, "pago"); carregar(); } catch(e) { setErro(e instanceof Error ? e.message : "Não foi possível atualizar."); } }
  async function lembrar(c: Cobranca) { if (!window.confirm(`Enviar lembrete de ${moeda.format(c.valor)} para ${c.cliente_nome} pelo WhatsApp?`)) return; try { setEnviando(c.id); await enviarLembreteCobranca(c.id); carregar(); } catch (e) { setErro(e instanceof Error ? e.message : "Não foi possível enviar o lembrete."); } finally { setEnviando(""); } }
  const pendentes = cobrancas.filter(c=>c.status !== "pago"); const totalPendente = pendentes.reduce((a,c)=>a+c.valor,0);
  return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">Locação imobiliária</p><h1 className="mt-1 text-2xl font-semibold text-slate-900">Cobranças</h1><p className="mt-1 text-sm text-slate-500">Gere aluguéis mensais, acompanhe pagamentos e envie lembretes.</p></div><input type="month" value={mes} onChange={e=>setMes(e.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-3"><Card className="p-4"><p className="text-sm text-slate-500">A receber</p><p className="mt-2 text-xl font-semibold text-amber-600">{moeda.format(totalPendente)}</p></Card><Card className="p-4"><p className="text-sm text-slate-500">Pendentes</p><p className="mt-2 text-xl font-semibold text-slate-800">{pendentes.length}</p></Card><Card className="p-4"><p className="text-sm text-slate-500">Lembretes enviados</p><p className="mt-2 text-xl font-semibold text-primary">{cobrancas.filter(c=>c.lembrete_enviado_em).length}</p></Card></div>
    <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-[360px_1fr]"><Card className="p-5"><div className="flex items-center gap-2"><CircleDollarSign className="text-primary" size={20}/><h2 className="font-semibold text-slate-800">Nova cobrança</h2></div><div className="mt-4 grid gap-3"><select value={form.imovel_id} onChange={e=>setForm({...form,imovel_id:e.target.value})} className="rounded-lg border border-slate-200 p-2.5 text-sm"><option value="">Selecione o imóvel alugado</option>{imoveis.map(i=><option key={i.id} value={i.id}>{i.titulo} — {i.cliente_nome}</option>)}</select>{selecionado && <p className="rounded-lg bg-indigo-50 px-3 py-2 text-xs text-primary">Valor sugerido: {moeda.format(selecionado.valor_aluguel + selecionado.taxa_condominio)}</p>}<input type="date" value={form.vencimento} onChange={e=>setForm({...form,vencimento:e.target.value})} className="rounded-lg border border-slate-200 p-2.5 text-sm"/><input value={form.valor} onChange={e=>setForm({...form,valor:e.target.value})} inputMode="decimal" placeholder="Valor diferente? (R$)" className="rounded-lg border border-slate-200 p-2.5 text-sm"/><Button onClick={criar}><Plus size={16}/> Gerar cobrança</Button></div><p className="mt-4 text-xs leading-relaxed text-slate-500">Os lembretes são enviados somente quando você clicar em “Enviar”. Isso evita cobrança indevida e dá controle total à imobiliária.</p></Card>
      <Card className="overflow-x-auto p-0"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-100 text-xs text-slate-400"><th className="px-5 py-3">Morador / imóvel</th><th className="px-4 py-3">Vencimento</th><th className="px-4 py-3">Valor</th><th className="px-4 py-3">Situação</th><th className="px-4 py-3"/></tr></thead><tbody>{cobrancas.length===0?<tr><td colSpan={5} className="px-5 py-14 text-center text-slate-400">Nenhuma cobrança nesta competência.</td></tr>:cobrancas.map(c=><tr key={c.id} className="border-b border-slate-50 last:border-0"><td className="px-5 py-3"><p className="font-medium text-slate-700">{c.cliente_nome}</p><p className="text-xs text-slate-400">{c.imovel_titulo}</p></td><td className="px-4 py-3 text-slate-600">{new Date(`${c.vencimento}T12:00:00`).toLocaleDateString("pt-BR")}</td><td className="px-4 py-3 font-medium text-slate-700">{moeda.format(c.valor)}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs ${c.status === "pago" ? "bg-emerald-50 text-emerald-700" : c.status === "atrasado" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{c.status}</span></td><td className="px-4 py-3"><div className="flex gap-2">{c.status !== "pago" && <button onClick={()=>pagar(c.id)} title="Marcar como pago" className="text-emerald-600"><Check size={18}/></button>}{c.status !== "pago" && <button onClick={()=>lembrar(c)} disabled={enviando===c.id} title="Enviar lembrete pelo WhatsApp" className="text-primary disabled:opacity-40">{c.lembrete_enviado_em ? <Bell size={18}/> : <Send size={18}/>}</button>}</div></td></tr>)}</tbody></table></Card></div>{erro && <p className="mt-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{erro}</p>}</div>;
}
