"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Download, FileText, FolderArchive, Search, Trash2, Upload } from "lucide-react";
import { API_URL, enviarDocumento, excluirDocumento, getDocumentos, type Documento } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

function tamanho(bytes: number) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`; }

export default function Documentos() {
  const [documentos, setDocumentos] = useState<Documento[]>([]); const [busca, setBusca] = useState(""); const [arquivo, setArquivo] = useState<File | null>(null); const [titulo, setTitulo] = useState(""); const [categoria, setCategoria] = useState("Geral"); const [erro, setErro] = useState(""); const inputRef = useRef<HTMLInputElement>(null);
  async function carregar() { try { setDocumentos(await getDocumentos()); } catch (causa) { setErro(causa instanceof Error ? causa.message : "Não foi possível carregar documentos."); } }
  useEffect(() => { carregar(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const filtrados = useMemo(() => { const termo = busca.toLowerCase(); return documentos.filter((item) => [item.titulo, item.categoria, item.nome_arquivo].some((valor) => valor.toLowerCase().includes(termo))); }, [busca, documentos]);
  async function enviar() { if (!arquivo || !titulo.trim()) { setErro("Escolha um arquivo e informe o título."); return; } try { await enviarDocumento(arquivo, titulo, categoria); setArquivo(null); setTitulo(""); setCategoria("Geral"); setErro(""); if (inputRef.current) inputRef.current.value = ""; carregar(); } catch (causa) { setErro(causa instanceof Error ? causa.message : "Não foi possível enviar o arquivo."); } }
  async function apagar(id: string) { if (window.confirm("Excluir este documento?")) { await excluirDocumento(id); carregar(); } }
  return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">Central de arquivos</p><h1 className="mt-1 text-2xl font-semibold text-slate-900">Documentos</h1><p className="mt-1 text-sm text-slate-500">Guarde contratos, propostas, documentos de clientes e arquivos do projeto.</p></div><div className="flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-2 text-sm font-medium text-primary"><FolderArchive size={16} /> {documentos.length} arquivo{documentos.length === 1 ? "" : "s"}</div></div>
    <Card className="mt-6 p-5"><div className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-50 text-primary"><Upload size={18} /></div><div><h2 className="font-semibold text-slate-800">Enviar documento</h2><p className="text-xs text-slate-500">PDF, imagem, planilha ou documento de até 20 MB.</p></div></div><div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-[1.2fr_1fr_1fr_auto]"><label className="cursor-pointer rounded-lg border border-dashed border-slate-300 px-3 py-2.5 text-sm text-slate-600 hover:border-primary">{arquivo ? arquivo.name : "Escolher arquivo"}<input ref={inputRef} type="file" className="hidden" onChange={(e) => setArquivo(e.target.files?.[0] ?? null)} /></label><input value={titulo} onChange={(e) => setTitulo(e.target.value)} placeholder="Título do documento" className="rounded-lg border border-slate-200 p-2.5 text-sm" /><select value={categoria} onChange={(e) => setCategoria(e.target.value)} className="rounded-lg border border-slate-200 p-2.5 text-sm"><option>Geral</option><option>Contrato</option><option>Proposta</option><option>Cliente</option><option>Financeiro</option><option>Terreno</option></select><Button onClick={enviar}><Upload size={16} /> Enviar</Button></div></Card>
    <Card className="mt-5 overflow-hidden p-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-4"><div><h2 className="font-semibold text-slate-800">Arquivos salvos</h2><p className="text-xs text-slate-500">{filtrados.length} resultado{filtrados.length === 1 ? "" : "s"}</p></div><label className="relative block"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Pesquisar documentos" className="w-64 max-w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-primary" /></label></div><div className="divide-y divide-slate-100">{filtrados.length === 0 ? <p className="p-12 text-center text-sm text-slate-400">{busca ? "Nenhum documento encontrado." : "Nenhum documento salvo ainda."}</p> : filtrados.map((item) => <div key={item.id} className="flex items-center gap-3 p-4 hover:bg-slate-50/70"><div className="rounded-lg bg-slate-100 p-2 text-slate-500"><FileText size={19} /></div><div className="min-w-0 flex-1"><p className="truncate font-medium text-slate-700">{item.titulo}</p><p className="truncate text-xs text-slate-500">{item.nome_arquivo} · {tamanho(item.tamanho_bytes)} · {new Date(item.criado_em).toLocaleDateString("pt-BR")}</p></div><span className="hidden rounded-full bg-indigo-50 px-2 py-1 text-xs text-indigo-700 sm:block">{item.categoria}</span><a href={`${API_URL}/documentos/${item.id}/download`} className="text-slate-500 hover:text-primary" title="Baixar"><Download size={18} /></a><button onClick={() => apagar(item.id)} className="text-slate-400 hover:text-red-600" title="Excluir"><Trash2 size={17} /></button></div>)}</div></Card>{erro && <p className="mt-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{erro}</p>}</div>;
}
