"use client";

import { Building2, MapPin, Search, SlidersHorizontal, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export default function LeadsAdmin() {
  return <div className="mx-auto max-w-7xl"><div className="flex items-start gap-3"><div className="rounded-xl bg-indigo-50 p-3 text-primary"><Target size={23} /></div><div><p className="text-sm font-medium text-primary">Administração Master</p><h1 className="mt-1 text-2xl font-semibold text-slate-900">Leads</h1><p className="mt-1 text-sm text-slate-500">Encontre imobiliárias e organize oportunidades comerciais.</p></div></div><Card className="mt-7 p-5"><div className="flex items-center gap-2"><span className="rounded-lg bg-indigo-50 p-2 text-primary"><Search size={18} /></span><div><h2 className="font-semibold text-slate-800">Pesquisar novos leads</h2><p className="text-xs text-slate-500">Defina o público-alvo para iniciar a prospecção.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-[1.2fr_1fr_1fr_auto]"><label className="relative"><MapPin size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input placeholder="Cidade ou região" className="w-full rounded-lg border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-primary" /></label><label className="relative"><Building2 size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input placeholder="Segmento: imobiliárias" defaultValue="Imobiliárias" className="w-full rounded-lg border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-primary" /></label><label className="relative"><SlidersHorizontal size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><select className="w-full appearance-none rounded-lg border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-primary"><option>Todos os portes</option><option>Pequena</option><option>Média</option><option>Grande</option></select></label><Button disabled title="Escolha a fonte de leads para ativar a busca"><Search size={16} />Buscar leads</Button></div><p className="mt-3 text-xs text-slate-500">A busca será ativada após configurar uma fonte autorizada de dados para prospecção.</p></Card><Card className="mt-5 overflow-hidden p-0"><div className="flex items-center justify-between border-b border-slate-100 p-4"><div><h2 className="font-semibold text-slate-800">Resultados</h2><p className="text-xs text-slate-500">Os leads encontrados aparecerão aqui para qualificação e contato.</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-500">0 leads</span></div><div className="grid place-items-center px-6 py-16 text-center"><div className="rounded-full bg-slate-100 p-4 text-slate-400"><Target size={28} /></div><h3 className="mt-4 font-medium text-slate-700">Pronto para iniciar a prospecção</h3><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Escolha a fonte de pesquisa e busque imobiliárias por região. Depois será possível registrar status, responsável e próximos contatos.</p></div></Card></div>;
}
